spring:
  application:
    name: ecommerce_web
  datasource:
    url: jdbc:mysql://localhost:3306/shopdevgo
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true